### ISSUE TITLE
Rotation is not working correctly

### ISSUE THREAD

**Issue by dimitar-lazarov** [jeremieweldin/JWSlideMenu#1]
Steps to reproduce:
1. Start the app in portrait mode
2. Go to third view
3. Rotate in landscape
4. Go back to first view.

Button and text on first view should be centered if the rotation is handled correctly. Unfortunately I don't know how ti fix this.

**Comment by jeremieweldin** [comment]
I can reproduce. I will look into this.

**Comment by dimitar-lazarov** [comment]
I think I've found the problem - the rotation is handled properly, but the view frame of controller that will be presented must be adjusted to the content's view size. I've created a pull request for that.

**Comment by jeremieweldin** [comment]
Excellent, thanks!  I'll apply the change tonight when I'm back in my home office.
